/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package java_assignment;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_assignment.Enums.OperatingDay;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AdmRegVen extends javax.swing.JFrame {

    User AdmUser = new User();
    private ArrayList<OperatingDay> days = new ArrayList<OperatingDay>();
    public AdmRegVen() throws IOException, ClassNotFoundException {
        initComponents();
        
        String userid = Java_assignment.LoggedInUser.getUserid();
        
        UserHandler admhandler = new UserHandler("User",User.class);
        
        this.AdmUser = admhandler.GetUserByUserID(userid);
        
        lblAdminName.setText(AdmUser.username);
        lblAdminNum.setText(AdmUser.userid);
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AMP_Right1 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblAdminName2 = new javax.swing.JLabel();
        lblAdminName3 = new javax.swing.JLabel();
        lblAdminName4 = new javax.swing.JLabel();
        lblAdminName5 = new javax.swing.JLabel();
        txtVenName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtVenID = new javax.swing.JTextField();
        txtConNum = new javax.swing.JTextField();
        lblAdminName6 = new javax.swing.JLabel();
        txtOpHrs = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblAdminName8 = new javax.swing.JLabel();
        cbMon = new javax.swing.JCheckBox();
        lblAdminName7 = new javax.swing.JLabel();
        cbWed = new javax.swing.JCheckBox();
        cbTue = new javax.swing.JCheckBox();
        cbThu = new javax.swing.JCheckBox();
        cbFri = new javax.swing.JCheckBox();
        cbSat = new javax.swing.JCheckBox();
        cbSun = new javax.swing.JCheckBox();
        AMP_Top1 = new javax.swing.JPanel();
        lb_quit2 = new javax.swing.JLabel();
        lb_logoName2 = new javax.swing.JLabel();
        lb_logoPic2 = new javax.swing.JLabel();
        AMP_Bottom1 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        lblAdminName = new javax.swing.JLabel();
        lblAdminNum = new javax.swing.JLabel();
        btnSettings1 = new javax.swing.JButton();
        btnTopUp1 = new javax.swing.JButton();
        btnRegistration1 = new javax.swing.JButton();
        btnDashboard1 = new javax.swing.JButton();
        btnNoti1 = new javax.swing.JButton();
        AMP_Left1 = new javax.swing.JPanel();
        lb_tuName2 = new javax.swing.JLabel();
        lb_tuName3 = new javax.swing.JLabel();
        lb_cafeName1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AMP_Right1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnRegister.setBackground(new java.awt.Color(0, 0, 0));
        btnRegister.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 204, 0));
        btnRegister.setText("Register");
        btnRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnCancel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 204, 0));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblAdminName2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblAdminName2.setForeground(new java.awt.Color(255, 204, 102));
        lblAdminName2.setText("Vendor Name:");

        lblAdminName3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblAdminName3.setForeground(new java.awt.Color(255, 204, 102));
        lblAdminName3.setText("Vendor ID:");

        lblAdminName4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblAdminName4.setForeground(new java.awt.Color(255, 204, 102));
        lblAdminName4.setText("Email Address:");

        lblAdminName5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblAdminName5.setForeground(new java.awt.Color(255, 204, 102));
        lblAdminName5.setText("Contact Number:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblAdminName6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblAdminName6.setForeground(new java.awt.Color(255, 204, 102));
        lblAdminName6.setText("Operating Hours:");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        lblAdminName8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblAdminName8.setForeground(new java.awt.Color(255, 204, 102));
        lblAdminName8.setText("Password:");

        cbMon.setText("Monday");
        cbMon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbMonStateChanged(evt);
            }
        });
        cbMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMonActionPerformed(evt);
            }
        });

        lblAdminName7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblAdminName7.setForeground(new java.awt.Color(255, 204, 102));
        lblAdminName7.setText("Operating Days:");

        cbWed.setText("Wednesday");
        cbWed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbWedActionPerformed(evt);
            }
        });

        cbTue.setText("Tuesday");
        cbTue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTueActionPerformed(evt);
            }
        });

        cbThu.setText("Thursday");
        cbThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbThuActionPerformed(evt);
            }
        });

        cbFri.setText("Friday");
        cbFri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFriActionPerformed(evt);
            }
        });

        cbSat.setText("Saturday");
        cbSat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSatActionPerformed(evt);
            }
        });

        cbSun.setText("Sunday");
        cbSun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AMP_Right1Layout = new javax.swing.GroupLayout(AMP_Right1);
        AMP_Right1.setLayout(AMP_Right1Layout);
        AMP_Right1Layout.setHorizontalGroup(
            AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AMP_Right1Layout.createSequentialGroup()
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AMP_Right1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AMP_Right1Layout.createSequentialGroup()
                                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAdminName3)
                                    .addComponent(lblAdminName2))
                                .addGap(39, 39, 39)
                                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVenName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVenID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblAdminName4)
                            .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(AMP_Right1Layout.createSequentialGroup()
                                    .addComponent(lblAdminName8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AMP_Right1Layout.createSequentialGroup()
                                    .addComponent(lblAdminName6)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtOpHrs, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AMP_Right1Layout.createSequentialGroup()
                                    .addComponent(lblAdminName5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtConNum, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblAdminName7)
                            .addGroup(AMP_Right1Layout.createSequentialGroup()
                                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AMP_Right1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AMP_Right1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbSat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbSun, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cbTue, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbWed, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbThu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AMP_Right1Layout.createSequentialGroup()
                                .addComponent(cbMon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(cbFri, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        AMP_Right1Layout.setVerticalGroup(
            AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AMP_Right1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminName3)
                    .addComponent(txtVenID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdminName2)
                    .addComponent(txtVenName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAdminName8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAdminName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminName5)
                    .addComponent(txtConNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdminName7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMon)
                    .addComponent(cbFri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTue)
                    .addComponent(cbSat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbWed)
                    .addComponent(cbSun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbThu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminName6)
                    .addComponent(txtOpHrs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        AMP_Top1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lb_quit2.setFont(new java.awt.Font("Myanmar Sangam MN", 1, 20)); // NOI18N
        lb_quit2.setText("X");
        lb_quit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_quit2MouseClicked(evt);
            }
        });

        lb_logoName2.setFont(new java.awt.Font("Josefin Sans", 1, 18)); // NOI18N
        lb_logoName2.setText("Tech University");

        lb_logoPic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tuCafeteria_logo.png"))); // NOI18N

        javax.swing.GroupLayout AMP_Top1Layout = new javax.swing.GroupLayout(AMP_Top1);
        AMP_Top1.setLayout(AMP_Top1Layout);
        AMP_Top1Layout.setHorizontalGroup(
            AMP_Top1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AMP_Top1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_logoPic2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_logoName2)
                .addGap(156, 156, 156)
                .addComponent(lb_quit2)
                .addGap(37, 37, 37))
        );
        AMP_Top1Layout.setVerticalGroup(
            AMP_Top1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AMP_Top1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(AMP_Top1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_logoPic2)
                    .addGroup(AMP_Top1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_logoName2)
                        .addComponent(lb_quit2)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        AMP_Bottom1.setBackground(new java.awt.Color(58, 54, 54));
        AMP_Bottom1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        filler2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAdminName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblAdminName.setForeground(new java.awt.Color(255, 204, 102));
        lblAdminName.setText("Admin Name");

        lblAdminNum.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblAdminNum.setForeground(new java.awt.Color(255, 204, 102));
        lblAdminNum.setText("Admin Num");

        btnSettings1.setBackground(new java.awt.Color(0, 0, 0));
        btnSettings1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/settings.png"))); // NOI18N
        btnSettings1.setText("jButton3");
        btnSettings1.setIconTextGap(-6);
        btnSettings1.setMaximumSize(new java.awt.Dimension(55, 55));
        btnSettings1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettings1ActionPerformed(evt);
            }
        });

        btnTopUp1.setBackground(new java.awt.Color(0, 0, 0));
        btnTopUp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/top up.png"))); // NOI18N
        btnTopUp1.setText("jButton3");
        btnTopUp1.setIconTextGap(-6);
        btnTopUp1.setMaximumSize(new java.awt.Dimension(55, 55));
        btnTopUp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopUp1ActionPerformed(evt);
            }
        });

        btnRegistration1.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistration1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registration.png"))); // NOI18N
        btnRegistration1.setText("jButton3");
        btnRegistration1.setIconTextGap(-6);
        btnRegistration1.setMaximumSize(new java.awt.Dimension(55, 55));
        btnRegistration1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistration1ActionPerformed(evt);
            }
        });

        btnDashboard1.setBackground(new java.awt.Color(0, 0, 0));
        btnDashboard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dashboard.png"))); // NOI18N
        btnDashboard1.setText("jButton3");
        btnDashboard1.setIconTextGap(-6);
        btnDashboard1.setMaximumSize(new java.awt.Dimension(55, 55));
        btnDashboard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboard1ActionPerformed(evt);
            }
        });

        btnNoti1.setBackground(new java.awt.Color(51, 51, 51));
        btnNoti1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/notifiactions.png"))); // NOI18N
        btnNoti1.setText("jButton3");
        btnNoti1.setIconTextGap(-6);
        btnNoti1.setMaximumSize(new java.awt.Dimension(55, 55));
        btnNoti1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoti1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AMP_Bottom1Layout = new javax.swing.GroupLayout(AMP_Bottom1);
        AMP_Bottom1.setLayout(AMP_Bottom1Layout);
        AMP_Bottom1Layout.setHorizontalGroup(
            AMP_Bottom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AMP_Bottom1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AMP_Bottom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdminNum, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminName))
                .addGap(55, 55, 55)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNoti1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistration1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTopUp1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSettings1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        AMP_Bottom1Layout.setVerticalGroup(
            AMP_Bottom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AMP_Bottom1Layout.createSequentialGroup()
                .addGroup(AMP_Bottom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AMP_Bottom1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(AMP_Bottom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSettings1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTopUp1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistration1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNoti1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AMP_Bottom1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblAdminName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdminNum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AMP_Left1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        AMP_Left1.setForeground(new java.awt.Color(204, 204, 204));

        lb_tuName2.setFont(new java.awt.Font("Josefin Sans", 1, 26)); // NOI18N
        lb_tuName2.setText("Tech");

        lb_tuName3.setFont(new java.awt.Font("Josefin Sans", 1, 26)); // NOI18N
        lb_tuName3.setText("University");

        lb_cafeName1.setFont(new java.awt.Font("Josefin Sans", 1, 26)); // NOI18N
        lb_cafeName1.setForeground(new java.awt.Color(255, 189, 49));
        lb_cafeName1.setText("Cafeteria");

        javax.swing.GroupLayout AMP_Left1Layout = new javax.swing.GroupLayout(AMP_Left1);
        AMP_Left1.setLayout(AMP_Left1Layout);
        AMP_Left1Layout.setHorizontalGroup(
            AMP_Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AMP_Left1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AMP_Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_tuName3)
                    .addComponent(lb_tuName2)
                    .addComponent(lb_cafeName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        AMP_Left1Layout.setVerticalGroup(
            AMP_Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AMP_Left1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_tuName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_tuName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_cafeName1)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AMP_Top1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AMP_Left1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AMP_Right1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(AMP_Bottom1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AMP_Top1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AMP_Left1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AMP_Right1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AMP_Bottom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
        AdmRegMain reg;
        try {
            reg = new AdmRegMain();
            reg.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdmRegAdm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdmRegAdm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void lb_quit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_quit2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lb_quit2MouseClicked

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnSettings1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettings1ActionPerformed
        this.dispose();
        AdmSettings sett;
        try {
            sett = new AdmSettings();
            sett.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdmRegCus.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdmRegCus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSettings1ActionPerformed

    private void btnNoti1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoti1ActionPerformed
        this.dispose();
        AdmNoti noti;
        try {
            noti = new AdmNoti();
            noti.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdmRegAdm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdmRegAdm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNoti1ActionPerformed

    private void btnDashboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard1ActionPerformed
        this.dispose();
        AdmMainPage main;
        try {
            main = new AdmMainPage();
            main.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdmRegAdm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdmRegAdm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDashboard1ActionPerformed

    private void btnRegistration1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistration1ActionPerformed
        this.dispose();
        AdmRegMain reg;
        try {
            reg = new AdmRegMain();
            reg.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdmRegAdm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdmRegAdm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistration1ActionPerformed

    private void btnTopUp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopUp1ActionPerformed
        this.dispose();
        AdmTopUp topup;
        try {
            topup = new AdmTopUp();
            topup.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdmRegAdm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdmRegAdm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnTopUp1ActionPerformed

    private void cbTueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTueActionPerformed
        days.add(OperatingDay.TUESDAY);
    }//GEN-LAST:event_cbTueActionPerformed

    private void cbMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMonActionPerformed
        days.add(OperatingDay.MONDAY);
    }//GEN-LAST:event_cbMonActionPerformed

    private void cbMonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbMonStateChanged
        
    }//GEN-LAST:event_cbMonStateChanged

    private void cbWedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbWedActionPerformed
        days.add(OperatingDay.WEDNESDAY);
    }//GEN-LAST:event_cbWedActionPerformed

    private void cbThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbThuActionPerformed
        days.add(OperatingDay.THURSDAY);
    }//GEN-LAST:event_cbThuActionPerformed

    private void cbFriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFriActionPerformed
        days.add(OperatingDay.FRIDAY);
    }//GEN-LAST:event_cbFriActionPerformed

    private void cbSatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSatActionPerformed
        days.add(OperatingDay.SATURDAY);
    }//GEN-LAST:event_cbSatActionPerformed

    private void cbSunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSunActionPerformed
        days.add(OperatingDay.SUNDAY);
    }//GEN-LAST:event_cbSunActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        User user = new User();
        Vendor ven = new Vendor();
        
        try {
            UserHandler ushan = new UserHandler("User",User.class);
            
            user.setUserid(txtVenID.getText()); 
            user.setUsername(txtVenName.getText());
            user.setPassword(txtPassword.getText());
            user.setEmail(txtEmail.getText()); 
            user.setHpnum(txtConNum.getText()); 
            user.setRole("Vendor");
            
            ushan.AddNewItem(user);
        } catch (IOException ex) {
            Logger.getLogger(AdmRegAdm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdmRegAdm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            VendorHandler venhan = new VendorHandler();
            
            ven.setVendorid(txtVenID.getText());
            ven.setVendorName(txtVenName.getText());
            ven.setOperatingDays(days);
            ven.setOperatingHours(txtOpHrs.getText());
            
            venhan.AddNewItem(ven);
            
        } catch (IOException ex) {
            Logger.getLogger(AdmRegAdm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdmRegAdm.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        txtVenID.setText("");
        txtVenName.setText("");
        txtPassword.setText("");
        txtEmail.setText("");
        txtConNum.setText("");
        JOptionPane.showMessageDialog(null,"Successfully Registered.");  
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmRegVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmRegVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmRegVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmRegVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdmRegVen().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AdmRegVen.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AdmRegVen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AMP_Bottom1;
    private javax.swing.JPanel AMP_Left1;
    private javax.swing.JPanel AMP_Right1;
    private javax.swing.JPanel AMP_Top1;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDashboard1;
    private javax.swing.JButton btnNoti1;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegistration1;
    private javax.swing.JButton btnSettings1;
    private javax.swing.JButton btnTopUp1;
    private javax.swing.JCheckBox cbFri;
    private javax.swing.JCheckBox cbMon;
    private javax.swing.JCheckBox cbSat;
    private javax.swing.JCheckBox cbSun;
    private javax.swing.JCheckBox cbThu;
    private javax.swing.JCheckBox cbTue;
    private javax.swing.JCheckBox cbWed;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel lb_cafeName1;
    private javax.swing.JLabel lb_logoName2;
    private javax.swing.JLabel lb_logoPic2;
    private javax.swing.JLabel lb_quit2;
    private javax.swing.JLabel lb_tuName2;
    private javax.swing.JLabel lb_tuName3;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JLabel lblAdminName2;
    private javax.swing.JLabel lblAdminName3;
    private javax.swing.JLabel lblAdminName4;
    private javax.swing.JLabel lblAdminName5;
    private javax.swing.JLabel lblAdminName6;
    private javax.swing.JLabel lblAdminName7;
    private javax.swing.JLabel lblAdminName8;
    private javax.swing.JLabel lblAdminNum;
    private javax.swing.JTextField txtConNum;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtOpHrs;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtVenID;
    private javax.swing.JTextField txtVenName;
    // End of variables declaration//GEN-END:variables

}
