/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_assignment;

/**
 *
 * @author User
 */
public class AdmUpdDelRun extends javax.swing.JFrame {

    /**
     * Creates new form AdmUpdDelRun
     */
    public AdmUpdDelRun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AMP_Top1 = new javax.swing.JPanel();
        lb_quit2 = new javax.swing.JLabel();
        lb_logoName2 = new javax.swing.JLabel();
        lb_logoPic2 = new javax.swing.JLabel();
        AMP_Left1 = new javax.swing.JPanel();
        lb_tuName2 = new javax.swing.JLabel();
        lb_tuName3 = new javax.swing.JLabel();
        lb_cafeName1 = new javax.swing.JLabel();
        AMP_Right1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblRunnerName = new javax.swing.JLabel();
        lblRunnerID = new javax.swing.JLabel();
        lblRunnerEmail = new javax.swing.JLabel();
        lblContNum = new javax.swing.JLabel();
        txtRunnerName = new javax.swing.JTextField();
        txtRunnerEmail = new javax.swing.JTextField();
        txtConNum = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        cmbRunnerID = new javax.swing.JComboBox<>();
        AMP_Bottom1 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        lblAdminName1 = new javax.swing.JLabel();
        lblAdminNum1 = new javax.swing.JLabel();
        btnSettings1 = new javax.swing.JButton();
        btnTopUp1 = new javax.swing.JButton();
        btnRegistration1 = new javax.swing.JButton();
        btnDashboard1 = new javax.swing.JButton();
        btnNoti1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AMP_Top1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lb_quit2.setFont(new java.awt.Font("Myanmar Sangam MN", 1, 20)); // NOI18N
        lb_quit2.setText("X");
        lb_quit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_quit2MouseClicked(evt);
            }
        });

        lb_logoName2.setFont(new java.awt.Font("Josefin Sans", 1, 18)); // NOI18N
        lb_logoName2.setText("Tech University");

        lb_logoPic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tuCafeteria_logo.png"))); // NOI18N

        javax.swing.GroupLayout AMP_Top1Layout = new javax.swing.GroupLayout(AMP_Top1);
        AMP_Top1.setLayout(AMP_Top1Layout);
        AMP_Top1Layout.setHorizontalGroup(
            AMP_Top1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AMP_Top1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_logoPic2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_logoName2)
                .addGap(145, 145, 145)
                .addComponent(lb_quit2)
                .addGap(37, 37, 37))
        );
        AMP_Top1Layout.setVerticalGroup(
            AMP_Top1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AMP_Top1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(AMP_Top1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_logoPic2)
                    .addGroup(AMP_Top1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_logoName2)
                        .addComponent(lb_quit2)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        AMP_Left1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        AMP_Left1.setForeground(new java.awt.Color(204, 204, 204));

        lb_tuName2.setFont(new java.awt.Font("Josefin Sans", 1, 26)); // NOI18N
        lb_tuName2.setText("Tech");

        lb_tuName3.setFont(new java.awt.Font("Josefin Sans", 1, 26)); // NOI18N
        lb_tuName3.setText("University");

        lb_cafeName1.setFont(new java.awt.Font("Josefin Sans", 1, 26)); // NOI18N
        lb_cafeName1.setForeground(new java.awt.Color(255, 189, 49));
        lb_cafeName1.setText("Cafeteria");

        javax.swing.GroupLayout AMP_Left1Layout = new javax.swing.GroupLayout(AMP_Left1);
        AMP_Left1.setLayout(AMP_Left1Layout);
        AMP_Left1Layout.setHorizontalGroup(
            AMP_Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AMP_Left1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AMP_Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_tuName3)
                    .addComponent(lb_tuName2)
                    .addComponent(lb_cafeName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        AMP_Left1Layout.setVerticalGroup(
            AMP_Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AMP_Left1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_tuName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_tuName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_cafeName1)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        AMP_Right1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 204, 0));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnCancel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 204, 0));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblRunnerName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblRunnerName.setForeground(new java.awt.Color(255, 204, 102));
        lblRunnerName.setText("Runner Name:");

        lblRunnerID.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblRunnerID.setForeground(new java.awt.Color(255, 204, 102));
        lblRunnerID.setText("Runner ID:");

        lblRunnerEmail.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblRunnerEmail.setForeground(new java.awt.Color(255, 204, 102));
        lblRunnerEmail.setText("Email Address:");

        lblContNum.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblContNum.setForeground(new java.awt.Color(255, 204, 102));
        lblContNum.setText("Contact Number:");

        txtRunnerName.setText("jTextField1");

        txtRunnerEmail.setText("jTextField1");
        txtRunnerEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRunnerEmailActionPerformed(evt);
            }
        });

        txtConNum.setText("jTextField1");

        txtPassword.setText("jTextField1");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 204, 102));
        lblPassword.setText("Password:");

        cmbRunnerID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout AMP_Right1Layout = new javax.swing.GroupLayout(AMP_Right1);
        AMP_Right1.setLayout(AMP_Right1Layout);
        AMP_Right1Layout.setHorizontalGroup(
            AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AMP_Right1Layout.createSequentialGroup()
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AMP_Right1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AMP_Right1Layout.createSequentialGroup()
                                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRunnerID)
                                    .addComponent(lblRunnerName))
                                .addGap(42, 42, 42)
                                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRunnerName, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(cmbRunnerID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblRunnerEmail)
                            .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtRunnerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(AMP_Right1Layout.createSequentialGroup()
                                    .addComponent(lblContNum)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtConNum, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AMP_Right1Layout.createSequentialGroup()
                                    .addComponent(lblPassword)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(AMP_Right1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AMP_Right1Layout.setVerticalGroup(
            AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AMP_Right1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunnerID)
                    .addComponent(cmbRunnerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRunnerName)
                    .addComponent(txtRunnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRunnerEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRunnerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContNum)
                    .addComponent(txtConNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AMP_Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        AMP_Bottom1.setBackground(new java.awt.Color(58, 54, 54));
        AMP_Bottom1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        filler2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAdminName1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblAdminName1.setForeground(new java.awt.Color(255, 204, 102));
        lblAdminName1.setText("Admin Name");

        lblAdminNum1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblAdminNum1.setForeground(new java.awt.Color(255, 204, 102));
        lblAdminNum1.setText("Admin Num");

        btnSettings1.setBackground(new java.awt.Color(0, 0, 0));
        btnSettings1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/settings.png"))); // NOI18N
        btnSettings1.setText("jButton3");
        btnSettings1.setIconTextGap(-6);
        btnSettings1.setMaximumSize(new java.awt.Dimension(55, 55));
        btnSettings1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettings1ActionPerformed(evt);
            }
        });

        btnTopUp1.setBackground(new java.awt.Color(0, 0, 0));
        btnTopUp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/top up.png"))); // NOI18N
        btnTopUp1.setText("jButton3");
        btnTopUp1.setIconTextGap(-6);
        btnTopUp1.setMaximumSize(new java.awt.Dimension(55, 55));
        btnTopUp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopUp1ActionPerformed(evt);
            }
        });

        btnRegistration1.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistration1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registration.png"))); // NOI18N
        btnRegistration1.setText("jButton3");
        btnRegistration1.setIconTextGap(-6);
        btnRegistration1.setMaximumSize(new java.awt.Dimension(55, 55));
        btnRegistration1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistration1ActionPerformed(evt);
            }
        });

        btnDashboard1.setBackground(new java.awt.Color(0, 0, 0));
        btnDashboard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dashboard.png"))); // NOI18N
        btnDashboard1.setText("jButton3");
        btnDashboard1.setIconTextGap(-6);
        btnDashboard1.setMaximumSize(new java.awt.Dimension(55, 55));
        btnDashboard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboard1ActionPerformed(evt);
            }
        });

        btnNoti1.setBackground(new java.awt.Color(51, 51, 51));
        btnNoti1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/notifiactions.png"))); // NOI18N
        btnNoti1.setText("jButton3");
        btnNoti1.setIconTextGap(-6);
        btnNoti1.setMaximumSize(new java.awt.Dimension(55, 55));
        btnNoti1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoti1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AMP_Bottom1Layout = new javax.swing.GroupLayout(AMP_Bottom1);
        AMP_Bottom1.setLayout(AMP_Bottom1Layout);
        AMP_Bottom1Layout.setHorizontalGroup(
            AMP_Bottom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AMP_Bottom1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AMP_Bottom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdminNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminName1))
                .addGap(55, 55, 55)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNoti1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistration1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTopUp1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSettings1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        AMP_Bottom1Layout.setVerticalGroup(
            AMP_Bottom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AMP_Bottom1Layout.createSequentialGroup()
                .addGroup(AMP_Bottom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AMP_Bottom1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(AMP_Bottom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSettings1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTopUp1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistration1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNoti1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AMP_Bottom1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblAdminName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdminNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AMP_Top1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AMP_Left1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AMP_Right1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(AMP_Bottom1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AMP_Top1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AMP_Left1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AMP_Right1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AMP_Bottom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_quit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_quit2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lb_quit2MouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
        AdmUpdMain retupddelrun = new AdmUpdMain();
        retupddelrun.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtRunnerEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRunnerEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRunnerEmailActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnNoti1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoti1ActionPerformed
        this.dispose();
        AdminNotifications noti2 = new AdminNotifications();
        noti2.setVisible(true); 
    }//GEN-LAST:event_btnNoti1ActionPerformed

    private void btnDashboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard1ActionPerformed
        this.dispose();
        AdminMainPage dashb = new AdminMainPage();
        dashb.setVisible(true); 
    }//GEN-LAST:event_btnDashboard1ActionPerformed

    private void btnRegistration1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistration1ActionPerformed
        this.dispose();
        AdminRegMain reg = new AdminRegMain();
        reg.setVisible(true); 
    }//GEN-LAST:event_btnRegistration1ActionPerformed

    private void btnTopUp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopUp1ActionPerformed
        this.dispose();
        AdminTopUp topup = new AdminTopUp();
        topup.setVisible(true);
    }//GEN-LAST:event_btnTopUp1ActionPerformed

    private void btnSettings1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettings1ActionPerformed
        this.dispose();
        AdminTopUp topup = new AdminTopUp();
        topup.setVisible(true);
    }//GEN-LAST:event_btnSettings1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmUpdDelRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmUpdDelRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmUpdDelRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmUpdDelRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmUpdDelRun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AMP_Bottom1;
    private javax.swing.JPanel AMP_Left1;
    private javax.swing.JPanel AMP_Right1;
    private javax.swing.JPanel AMP_Top1;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDashboard1;
    private javax.swing.JButton btnNoti1;
    private javax.swing.JButton btnRegistration1;
    private javax.swing.JButton btnSettings1;
    private javax.swing.JButton btnTopUp1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbRunnerID;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel lb_cafeName1;
    private javax.swing.JLabel lb_logoName2;
    private javax.swing.JLabel lb_logoPic2;
    private javax.swing.JLabel lb_quit2;
    private javax.swing.JLabel lb_tuName2;
    private javax.swing.JLabel lb_tuName3;
    private javax.swing.JLabel lblAdminName1;
    private javax.swing.JLabel lblAdminNum1;
    private javax.swing.JLabel lblContNum;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRunnerEmail;
    private javax.swing.JLabel lblRunnerID;
    private javax.swing.JLabel lblRunnerName;
    private javax.swing.JTextField txtConNum;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRunnerEmail;
    private javax.swing.JTextField txtRunnerName;
    // End of variables declaration//GEN-END:variables
}
